/****************************************************************************
**
** Copyright (C) 2019 Robert Vetter.
**
** This file is part of the MagicstompFrenzy - an editor for Yamaha Magicstomp
** effect processor
**
** THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
** ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
** IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
** PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
**
** GNU General Public License Usage
** This file may be used under the terms of the GNU
** General Public License version 2.0 or (at your option) the GNU General
** Public license version 3 or any later version . The licenses are
** as published by the Free Software Foundation and appearing in the file LICENSE
** included in the packaging of this file. Please review the following
** information to ensure the GNU General Public License requirements will
** be met: https://www.gnu.org/licenses/gpl-2.0.html and
** https://www.gnu.org/licenses/gpl-3.0.html.
**/

#ifndef KNOBPARAMETERS_H
#define KNOBPARAMETERS_H

#include <QMap>
#include <QString>

const QMap<int, QString> AcousticMultiKnobParameters =
{
    { 11, QStringLiteral("Type") },
    { 19, QStringLiteral("Blend") },
    { 20, QStringLiteral("Bass") },
    { 21, QStringLiteral("Middle") },
    { 22, QStringLiteral("Treble") },
    { 23, QStringLiteral("Presence") },
    { 24, QStringLiteral("Volume") },
    { 25, QStringLiteral("Stereo") },
    { 26, QStringLiteral("Bass Freq") },
    { 27, QStringLiteral("Middle Freq") },
    { 28, QStringLiteral("Treble Freq") },
    { 29, QStringLiteral("Presence Freq") },
    { 30, QStringLiteral("Limiter On/Off") },
    { 32, QStringLiteral("Chorus/Delay Type") },
    { 34, QStringLiteral("Reverb Type") },
    { 36, QStringLiteral("Limiter") },
    { 37, QStringLiteral("Speed/Time") },
    { 38, QStringLiteral("Depth/Feedback") },
    { 39, QStringLiteral("Chorus/Delay Level") },
    { 40, QStringLiteral("Reverb Level") }
};

const QMap<int, QString> EightBandParaDlyKnobParameters =
{
    { 0, QStringLiteral("Band 1 Delay Time") },
    { 1, QStringLiteral("Band 2 Delay Time") },
    { 2, QStringLiteral("Band 3 Delay Time") },
    { 3, QStringLiteral("Band 4 Delay Time") },
    { 4, QStringLiteral("Band 5 Delay Time") },
    { 5, QStringLiteral("Band 6 Delay Time") },
    { 6, QStringLiteral("Band 7 Delay Time") },
    { 7, QStringLiteral("Band 8 Delay Time") },
    { 8, QStringLiteral("Effect Level") },
    { 9, QStringLiteral("Direct Level") },
    { 10, QStringLiteral("Direct Pan") },
    { 11, QStringLiteral("Wave Form") },

    { 19, QStringLiteral("Band 1 Low Cut Filter") },
    { 20, QStringLiteral("Band 1 High Cut Filter") },
    { 21, QStringLiteral("Band 1 Feedback") },
    { 22, QStringLiteral("Band 1 Wave") },
    { 23, QStringLiteral("Band 1 Phase") },
    { 24, QStringLiteral("Band 1 Tap") },
    { 25, QStringLiteral("Band 1 Speed") },
    { 26, QStringLiteral("Band 1 Depth") },
    { 27, QStringLiteral("Band 1 Pan") },
    { 28, QStringLiteral("Band 1 Level") },
    { 29, QStringLiteral("Band 1 Sync") },

    { 30, QStringLiteral("Band 2 Low Cut Filter") },
    { 31, QStringLiteral("Band 2 High Cut Filter") },
    { 32, QStringLiteral("Band 2 Feedback") },
    { 33, QStringLiteral("Band 2 Wave") },
    { 34, QStringLiteral("Band 2 Phase") },
    { 35, QStringLiteral("Band 2 Tap") },
    { 36, QStringLiteral("Band 2 Speed") },
    { 37, QStringLiteral("Band 2 Depth") },
    { 38, QStringLiteral("Band 2 Pan") },
    { 39, QStringLiteral("Band 2 Level") },
    { 40, QStringLiteral("Band 2 Sync") },

    { 41, QStringLiteral("Band 3 Low Cut Filter") },
    { 42, QStringLiteral("Band 3 High Cut Filter") },
    { 43, QStringLiteral("Band 3 Feedback") },
    { 44, QStringLiteral("Band 3 Wave") },
    { 45, QStringLiteral("Band 3 Phase") },
    { 46, QStringLiteral("Band 3 Tap") },
    { 47, QStringLiteral("Band 3 Speed") },
    { 48, QStringLiteral("Band 3 Depth") },
    { 49, QStringLiteral("Band 3 Pan") },
    { 50, QStringLiteral("Band 3 Level") },
    { 51, QStringLiteral("Band 3 Sync") },

    { 52, QStringLiteral("Band 4 Low Cut Filter") },
    { 53, QStringLiteral("Band 4 High Cut Filter") },
    { 54, QStringLiteral("Band 4 Feedback") },
    { 55, QStringLiteral("Band 4 Wave") },
    { 56, QStringLiteral("Band 4 Phase") },
    { 57, QStringLiteral("Band 4 Tap") },
    { 58, QStringLiteral("Band 4 Speed") },
    { 59, QStringLiteral("Band 4 Depth") },
    { 60, QStringLiteral("Band 4 Pan") },
    { 61, QStringLiteral("Band 4 Level") },
    { 62, QStringLiteral("Band 4 Sync") },

    { 63, QStringLiteral("Band 5 Low Cut Filter") },
    { 64, QStringLiteral("Band 5 High Cut Filter") },
    { 65, QStringLiteral("Band 5 Feedback") },
    { 66, QStringLiteral("Band 5 Wave") },
    { 67, QStringLiteral("Band 5 Phase") },
    { 68, QStringLiteral("Band 5 Tap") },
    { 69, QStringLiteral("Band 5 Speed") },
    { 70, QStringLiteral("Band 5 Depth") },
    { 71, QStringLiteral("Band 5 Pan") },
    { 72, QStringLiteral("Band 5 Level") },
    { 73, QStringLiteral("Band 5 Sync") },

    { 74, QStringLiteral("Band 6 Low Cut Filter") },
    { 75, QStringLiteral("Band 6 High Cut Filter") },
    { 76, QStringLiteral("Band 6 Feedback") },
    { 77, QStringLiteral("Band 6 Wave") },
    { 78, QStringLiteral("Band 6 Phase") },
    { 79, QStringLiteral("Band 6 Tap") },
    { 80, QStringLiteral("Band 6 Speed") },
    { 81, QStringLiteral("Band 6 Depth") },
    { 82, QStringLiteral("Band 6 Pan") },
    { 83, QStringLiteral("Band 6 Level") },
    { 84, QStringLiteral("Band 6 Sync") },

    { 85, QStringLiteral("Band 7 Low Cut Filter") },
    { 86, QStringLiteral("Band 7 High Cut Filter") },
    { 87, QStringLiteral("Band 7 Feedback") },
    { 88, QStringLiteral("Band 7 Wave") },
    { 89, QStringLiteral("Band 7 Phase") },
    { 90, QStringLiteral("Band 7 Tap") },
    { 91, QStringLiteral("Band 7 Speed") },
    { 92, QStringLiteral("Band 7 Depth") },
    { 93, QStringLiteral("Band 7 Pan") },
    { 94, QStringLiteral("Band 7 Level") },
    { 95, QStringLiteral("Band 7 Sync") },

    { 96, QStringLiteral("Band 8 Low Cut Filter") },
    { 97, QStringLiteral("Band 8 High Cut Filter") },
    { 98, QStringLiteral("Band 8 Feedback") },
    { 99, QStringLiteral("Band 8 Wave") },
    {100, QStringLiteral("Band 8 Phase") },
    {101, QStringLiteral("Band 8 Tap") },
    {102, QStringLiteral("Band 8 Speed") },
    {103, QStringLiteral("Band 8 Depth") },
    {104, QStringLiteral("Band 8 Pan") },
    {105, QStringLiteral("Band 8 Level") },
    {106, QStringLiteral("Band 8 Sync") }
};

const QMap<int, QString> FourBand2TapModDlyKnobParameters =
{
    { 0, QStringLiteral("Band 1 Delay Time") },
    { 2, QStringLiteral("Band 2 Delay Time") },
    { 4, QStringLiteral("Band 3 Delay Time") },
    { 6, QStringLiteral("Band 4 Delay Time") },
    { 8, QStringLiteral("Effect Level") },
    { 9, QStringLiteral("Direct Level") },
    { 10, QStringLiteral("Direct Pan") },
    { 11, QStringLiteral("Wave Form") },

    { 19, QStringLiteral("Band 1 Tap 1 Low Cut Filter") },
    { 20, QStringLiteral("Band 1 Tap 1 High Cut Filter") },
    { 21, QStringLiteral("Band 1 Tap 1 Feedback") },
    { 22, QStringLiteral("Band 1 Tap 1 Wave") },
    { 23, QStringLiteral("Band 1 Tap 1 Phase") },
    { 24, QStringLiteral("Band 1 Tap 1 Tap") },
    { 25, QStringLiteral("Band 1 Tap 1 Speed") },
    { 26, QStringLiteral("Band 1 Tap 1 Depth") },
    { 27, QStringLiteral("Band 1 Tap 1 Pan") },
    { 28, QStringLiteral("Band 1 Tap 1 Level") },
    { 29, QStringLiteral("Band 1 Tap 1 Sync") },

    { 33, QStringLiteral("Band 1 Tap 2 Wave") },
    { 34, QStringLiteral("Band 1 Tap 2 Phase") },
    { 35, QStringLiteral("Band 1 Tap 2 Tap") },
    { 36, QStringLiteral("Band 1 Tap 2 Speed") },
    { 37, QStringLiteral("Band 1 Tap 2 Depth") },
    { 38, QStringLiteral("Band 1 Tap 2 Pan") },
    { 39, QStringLiteral("Band 1 Tap 2 Level") },
    { 40, QStringLiteral("Band 1 Tap 2 Sync") },

    { 41, QStringLiteral("Band 2 Tap 1 Low Cut Filter") },
    { 42, QStringLiteral("Band 2 Tap 1 High Cut Filter") },
    { 43, QStringLiteral("Band 2 Tap 1 Feedback") },
    { 44, QStringLiteral("Band 2 Tap 1 Wave") },
    { 45, QStringLiteral("Band 2 Tap 1 Phase") },
    { 46, QStringLiteral("Band 2 Tap 1 Tap") },
    { 47, QStringLiteral("Band 2 Tap 1 Speed") },
    { 48, QStringLiteral("Band 2 Tap 1 Depth") },
    { 49, QStringLiteral("Band 2 Tap 1 Pan") },
    { 50, QStringLiteral("Band 2 Tap 1 Level") },
    { 51, QStringLiteral("Band 2 Tap 1 Sync") },

    { 55, QStringLiteral("Band 2 Tap 2 Wave") },
    { 56, QStringLiteral("Band 2 Tap 2 Phase") },
    { 57, QStringLiteral("Band 2 Tap 2 Tap") },
    { 58, QStringLiteral("Band 2 Tap 2 Speed") },
    { 59, QStringLiteral("Band 2 Tap 2 Depth") },
    { 60, QStringLiteral("Band 2 Tap 2 Pan") },
    { 61, QStringLiteral("Band 2 Tap 2 Level") },
    { 62, QStringLiteral("Band 2 Tap 2 Sync") },

    { 63, QStringLiteral("Band 3 Tap 1 Low Cut Filter") },
    { 64, QStringLiteral("Band 3 Tap 1 High Cut Filter") },
    { 65, QStringLiteral("Band 3 Tap 1 Feedback") },
    { 66, QStringLiteral("Band 3 Tap 1 Wave") },
    { 67, QStringLiteral("Band 3 Tap 1 Phase") },
    { 68, QStringLiteral("Band 3 Tap 1 Tap") },
    { 69, QStringLiteral("Band 3 Tap 1 Speed") },
    { 70, QStringLiteral("Band 3 Tap 1 Depth") },
    { 71, QStringLiteral("Band 3 Tap 1 Pan") },
    { 72, QStringLiteral("Band 3 Tap 1 Level") },
    { 73, QStringLiteral("Band 3 Tap 1 Sync") },

    { 77, QStringLiteral("Band 3 Tap 2 Wave") },
    { 78, QStringLiteral("Band 3 Tap 2 Phase") },
    { 79, QStringLiteral("Band 3 Tap 2 Tap") },
    { 80, QStringLiteral("Band 3 Tap 2 Speed") },
    { 81, QStringLiteral("Band 3 Tap 2 Depth") },
    { 82, QStringLiteral("Band 3 Tap 2 Pan") },
    { 83, QStringLiteral("Band 3 Tap 2 Level") },
    { 84, QStringLiteral("Band 3 Tap 2 Sync") },

    { 85, QStringLiteral("Band 4 Tap 1 Low Cut Filter") },
    { 86, QStringLiteral("Band 4 Tap 1 High Cut Filter") },
    { 87, QStringLiteral("Band 4 Tap 1 Feedback") },
    { 88, QStringLiteral("Band 4 Tap 1 Wave") },
    { 89, QStringLiteral("Band 4 Tap 1 Phase") },
    { 90, QStringLiteral("Band 4 Tap 1 Tap") },
    { 91, QStringLiteral("Band 4 Tap 1 Speed") },
    { 92, QStringLiteral("Band 4 Tap 1 Depth") },
    { 93, QStringLiteral("Band 4 Tap 1 Pan") },
    { 94, QStringLiteral("Band 4 Tap 1 Level") },
    { 95, QStringLiteral("Band 4 Tap 1 Sync") },

    { 99, QStringLiteral("Band 4 Tap 2 Wave") },
    {100, QStringLiteral("Band 4 Tap 2 Phase") },
    {101, QStringLiteral("Band 4 Tap 2 Tap") },
    {102, QStringLiteral("Band 4 Tap 2 Speed") },
    {103, QStringLiteral("Band 4 Tap 2 Depth") },
    {104, QStringLiteral("Band 4 Tap 2 Pan") },
    {105, QStringLiteral("Band 4 Tap 2 Level") },
    {106, QStringLiteral("Band 4 Tap 2 Sync") }
};

const QMap<int, QString> TwoBand4TapModDlyKnobParameters =
{
    { 0, QStringLiteral("Band 1 Delay Time") },
    { 4, QStringLiteral("Band 2 Delay Time") },
    { 8, QStringLiteral("Effect Level") },
    { 9, QStringLiteral("Direct Level") },
    { 10, QStringLiteral("Direct Pan") },
    { 11, QStringLiteral("Wave Form") },

    { 19, QStringLiteral("Band 1 Tap 1 Low Cut Filter") },
    { 20, QStringLiteral("Band 1 Tap 1 High Cut Filter") },
    { 21, QStringLiteral("Band 1 Tap 1 Feedback") },
    { 22, QStringLiteral("Band 1 Tap 1 Wave") },
    { 23, QStringLiteral("Band 1 Tap 1 Phase") },
    { 24, QStringLiteral("Band 1 Tap 1 Tap") },
    { 25, QStringLiteral("Band 1 Tap 1 Speed") },
    { 26, QStringLiteral("Band 1 Tap 1 Depth") },
    { 27, QStringLiteral("Band 1 Tap 1 Pan") },
    { 28, QStringLiteral("Band 1 Tap 1 Level") },
    { 29, QStringLiteral("Band 1 Tap 1 Sync") },

    { 33, QStringLiteral("Band 1 Tap 2 Wave") },
    { 34, QStringLiteral("Band 1 Tap 2 Phase") },
    { 35, QStringLiteral("Band 1 Tap 2 Tap") },
    { 36, QStringLiteral("Band 1 Tap 2 Speed") },
    { 37, QStringLiteral("Band 1 Tap 2 Depth") },
    { 38, QStringLiteral("Band 1 Tap 2 Pan") },
    { 39, QStringLiteral("Band 1 Tap 2 Level") },
    { 40, QStringLiteral("Band 1 Tap 2 Sync") },

    { 44, QStringLiteral("Band 1 Tap 3 Wave") },
    { 45, QStringLiteral("Band 1 Tap 3 Phase") },
    { 46, QStringLiteral("Band 1 Tap 3 Tap") },
    { 47, QStringLiteral("Band 1 Tap 3 Speed") },
    { 48, QStringLiteral("Band 1 Tap 3 Depth") },
    { 49, QStringLiteral("Band 1 Tap 3 Pan") },
    { 50, QStringLiteral("Band 1 Tap 3 Level") },
    { 51, QStringLiteral("Band 1 Tap 3 Sync") },

    { 55, QStringLiteral("Band 1 Tap 4 Wave") },
    { 56, QStringLiteral("Band 1 Tap 4 Phase") },
    { 57, QStringLiteral("Band 1 Tap 4 Tap") },
    { 58, QStringLiteral("Band 1 Tap 4 Speed") },
    { 59, QStringLiteral("Band 1 Tap 4 Depth") },
    { 60, QStringLiteral("Band 1 Tap 4 Pan") },
    { 61, QStringLiteral("Band 1 Tap 4 Level") },
    { 62, QStringLiteral("Band 1 Tap 4 Sync") },

    { 63, QStringLiteral("Band 2 Tap 1 Low Cut Filter") },
    { 64, QStringLiteral("Band 2 Tap 1 High Cut Filter") },
    { 65, QStringLiteral("Band 2 Tap 1 Feedback") },
    { 66, QStringLiteral("Band 2 Tap 1 Wave") },
    { 67, QStringLiteral("Band 2 Tap 1 Phase") },
    { 68, QStringLiteral("Band 2 Tap 1 Tap") },
    { 69, QStringLiteral("Band 2 Tap 1 Speed") },
    { 70, QStringLiteral("Band 2 Tap 1 Depth") },
    { 71, QStringLiteral("Band 2 Tap 1 Pan") },
    { 72, QStringLiteral("Band 2 Tap 1 Level") },
    { 73, QStringLiteral("Band 2 Tap 1 Sync") },

    { 77, QStringLiteral("Band 2 Tap 2 Wave") },
    { 78, QStringLiteral("Band 2 Tap 2 Phase") },
    { 79, QStringLiteral("Band 2 Tap 2 Tap") },
    { 80, QStringLiteral("Band 2 Tap 2 Speed") },
    { 81, QStringLiteral("Band 2 Tap 2 Depth") },
    { 82, QStringLiteral("Band 2 Tap 2 Pan") },
    { 83, QStringLiteral("Band 2 Tap 2 Level") },
    { 84, QStringLiteral("Band 2 Tap 2 Sync") },

    { 88, QStringLiteral("Band 2 Tap 3 Wave") },
    { 89, QStringLiteral("Band 2 Tap 3 Phase") },
    { 90, QStringLiteral("Band 2 Tap 3 Tap") },
    { 91, QStringLiteral("Band 2 Tap 3 Speed") },
    { 92, QStringLiteral("Band 2 Tap 3 Depth") },
    { 93, QStringLiteral("Band 2 Tap 3 Pan") },
    { 94, QStringLiteral("Band 2 Tap 3 Level") },
    { 95, QStringLiteral("Band 2 Tap 3 Sync") },

    { 99, QStringLiteral("Band 2 Tap 4 Wave") },
    {100, QStringLiteral("Band 2 Tap 4 Phase") },
    {101, QStringLiteral("Band 2 Tap 4 Tap") },
    {102, QStringLiteral("Band 2 Tap 4 Speed") },
    {103, QStringLiteral("Band 2 Tap 4 Depth") },
    {104, QStringLiteral("Band 2 Tap 4 Pan") },
    {105, QStringLiteral("Band 2 Tap 4 Level") },
    {106, QStringLiteral("Band 2 Tap 4 Sync") }
};

const QMap<int, QString> OneBand8TapModDlyKnobParameters =
{
    { 0, QStringLiteral("Band 1 Delay Time") },
    { 8, QStringLiteral("Effect Level") },
    { 9, QStringLiteral("Direct Level") },
    { 10, QStringLiteral("Direct Pan") },
    { 11, QStringLiteral("Wave Form") },

    { 19, QStringLiteral("Tap 1 Low Cut Filter") },
    { 20, QStringLiteral("Tap 1 High Cut Filter") },
    { 21, QStringLiteral("Tap 1 Feedback") },
    { 22, QStringLiteral("Tap 1 Wave") },
    { 23, QStringLiteral("Tap 1 Phase") },
    { 24, QStringLiteral("Tap 1 Tap") },
    { 25, QStringLiteral("Tap 1 Speed") },
    { 26, QStringLiteral("Tap 1 Depth") },
    { 27, QStringLiteral("Tap 1 Pan") },
    { 28, QStringLiteral("Tap 1 Level") },
    { 29, QStringLiteral("Tap 1 Sync") },

    { 33, QStringLiteral("Tap 2 Wave") },
    { 34, QStringLiteral("Tap 2 Phase") },
    { 35, QStringLiteral("Tap 2 Tap") },
    { 36, QStringLiteral("Tap 2 Speed") },
    { 37, QStringLiteral("Tap 2 Depth") },
    { 38, QStringLiteral("Tap 2 Pan") },
    { 39, QStringLiteral("Tap 2 Level") },
    { 40, QStringLiteral("Tap 2 Sync") },

    { 44, QStringLiteral("Tap 3 Wave") },
    { 45, QStringLiteral("Tap 3 Phase") },
    { 46, QStringLiteral("Tap 3 Tap") },
    { 47, QStringLiteral("Tap 3 Speed") },
    { 48, QStringLiteral("Tap 3 Depth") },
    { 49, QStringLiteral("Tap 3 Pan") },
    { 50, QStringLiteral("Tap 3 Level") },
    { 51, QStringLiteral("Tap 3 Sync") },

    { 55, QStringLiteral("Tap 4 Wave") },
    { 56, QStringLiteral("Tap 4 Phase") },
    { 57, QStringLiteral("Tap 4 Tap") },
    { 58, QStringLiteral("Tap 4 Speed") },
    { 59, QStringLiteral("Tap 4 Depth") },
    { 60, QStringLiteral("Tap 4 Pan") },
    { 61, QStringLiteral("Tap 4 Level") },
    { 62, QStringLiteral("Tap 4 Sync") },

    { 66, QStringLiteral("Tap 5 Wave") },
    { 67, QStringLiteral("Tap 5 Phase") },
    { 68, QStringLiteral("Tap 5 Tap") },
    { 69, QStringLiteral("Tap 5 Speed") },
    { 70, QStringLiteral("Tap 5 Depth") },
    { 71, QStringLiteral("Tap 5 Pan") },
    { 72, QStringLiteral("Tap 5 Level") },
    { 73, QStringLiteral("Tap 5 Sync") },

    { 77, QStringLiteral("Tap 6 Wave") },
    { 78, QStringLiteral("Tap 6 Phase") },
    { 79, QStringLiteral("Tap 6 Tap") },
    { 80, QStringLiteral("Tap 6 Speed") },
    { 81, QStringLiteral("Tap 6 Depth") },
    { 82, QStringLiteral("Tap 6 Pan") },
    { 83, QStringLiteral("Tap 6 Level") },
    { 84, QStringLiteral("Tap 6 Sync") },

    { 88, QStringLiteral("Tap 7 Wave") },
    { 89, QStringLiteral("Tap 7 Phase") },
    { 90, QStringLiteral("Tap 7 Tap") },
    { 91, QStringLiteral("Tap 7 Speed") },
    { 92, QStringLiteral("Tap 7 Depth") },
    { 93, QStringLiteral("Tap 7 Pan") },
    { 94, QStringLiteral("Tap 7 Level") },
    { 95, QStringLiteral("Tap 7 Sync") },

    { 99, QStringLiteral("Tap 8 Wave") },
    {100, QStringLiteral("Tap 8 Phase") },
    {101, QStringLiteral("Tap 8 Tap") },
    {102, QStringLiteral("Tap 8 Speed") },
    {103, QStringLiteral("Tap 8 Depth") },
    {104, QStringLiteral("Tap 8 Pan") },
    {105, QStringLiteral("Tap 8 Level") },
    {106, QStringLiteral("Tap 8 Sync") }
};

const QMap<int, QString> TwoBandLong4ShortModDlyKnobParameters =
{
    { 0, QStringLiteral("Long Band 1 Delay Time") },
    { 2, QStringLiteral("Long Band 2 Delay Time") },
    { 4, QStringLiteral("Short Band 1 Delay Time") },
    { 5, QStringLiteral("Short Band 2 Delay Time") },
    { 6, QStringLiteral("Short Band 3 Delay Time") },
    { 7, QStringLiteral("Short Band 4 Short Delay Time") },
    { 8, QStringLiteral("Effect Level") },
    { 9, QStringLiteral("Direct Level") },
    { 10, QStringLiteral("Direct Pan") },
    { 11, QStringLiteral("Wave Form") },

    { 19, QStringLiteral("Long Band 1 Tap 1 Low Cut Filter") },
    { 20, QStringLiteral("Long Band 1 Tap 1 High Cut Filter") },
    { 21, QStringLiteral("Long Band 1 Tap 1 Feedback") },
    { 22, QStringLiteral("Long Band 1 Tap 1 Wave") },
    { 23, QStringLiteral("Long Band 1 Tap 1 Phase") },
    { 24, QStringLiteral("Long Band 1 Tap 1 Tap") },
    { 25, QStringLiteral("Long Band 1 Tap 1 Speed") },
    { 26, QStringLiteral("Long Band 1 Tap 1 Depth") },
    { 27, QStringLiteral("Long Band 1 Tap 1 Pan") },
    { 28, QStringLiteral("Long Band 1 Tap 1 Level") },
    { 29, QStringLiteral("Long Band 1 Tap 1 Sync") },

    { 33, QStringLiteral("Long Band 1 Tap 2 Wave") },
    { 34, QStringLiteral("Long Band 1 Tap 2 Phase") },
    { 35, QStringLiteral("Long Band 1 Tap 2 Tap") },
    { 36, QStringLiteral("Long Band 1 Tap 2 Speed") },
    { 37, QStringLiteral("Long Band 1 Tap 2 Depth") },
    { 38, QStringLiteral("Long Band 1 Tap 2 Pan") },
    { 39, QStringLiteral("Long Band 1 Tap 2 Level") },
    { 40, QStringLiteral("Long Band 1 Tap 2 Sync") },

    { 41, QStringLiteral("Long Band 2 Tap 1 Low Cut Filter") },
    { 42, QStringLiteral("Long Band 2 Tap 1 High Cut Filter") },
    { 43, QStringLiteral("Long Band 2 Tap 1 Feedback") },
    { 44, QStringLiteral("Long Band 2 Tap 1 Wave") },
    { 45, QStringLiteral("Long Band 2 Tap 1 Phase") },
    { 46, QStringLiteral("Long Band 2 Tap 1 Tap") },
    { 47, QStringLiteral("Long Band 2 Tap 1 Speed") },
    { 48, QStringLiteral("Long Band 2 Tap 1 Depth") },
    { 49, QStringLiteral("Long Band 2 Tap 1 Pan") },
    { 50, QStringLiteral("Long Band 2 Tap 1 Level") },
    { 51, QStringLiteral("Long Band 2 Tap 1 Sync") },

    { 55, QStringLiteral("Long Band 2 Tap 2 Wave") },
    { 56, QStringLiteral("Long Band 2 Tap 2 Phase") },
    { 57, QStringLiteral("Long Band 2 Tap 2 Tap") },
    { 58, QStringLiteral("Long Band 2 Tap 2 Speed") },
    { 59, QStringLiteral("Long Band 2 Tap 2 Depth") },
    { 60, QStringLiteral("Long Band 2 Tap 2 Pan") },
    { 61, QStringLiteral("Long Band 2 Tap 2 Level") },
    { 62, QStringLiteral("Long Band 2 Tap 2 Sync") },

    { 63, QStringLiteral("Short Band 1 Low Cut Filter") },
    { 64, QStringLiteral("Short Band 1 High Cut Filter") },
    { 65, QStringLiteral("Short Band 1 Feedback") },
    { 66, QStringLiteral("Short Band 1 Wave") },
    { 67, QStringLiteral("Short Band 1 Phase") },
    { 68, QStringLiteral("Short Band 1 Tap") },
    { 69, QStringLiteral("Short Band 1 Speed") },
    { 70, QStringLiteral("Short Band 1 Depth") },
    { 71, QStringLiteral("Short Band 1 Pan") },
    { 72, QStringLiteral("Short Band 1 Level") },
    { 73, QStringLiteral("Short Band 1 Sync") },

    { 74, QStringLiteral("Short Band 2 Low Cut Filter") },
    { 75, QStringLiteral("Short Band 2 High Cut Filter") },
    { 76, QStringLiteral("Short Band 2 Feedback") },
    { 77, QStringLiteral("Short Band 2 Wave") },
    { 78, QStringLiteral("Short Band 2 Phase") },
    { 79, QStringLiteral("Short Band 2 Tap") },
    { 80, QStringLiteral("Short Band 2 Speed") },
    { 81, QStringLiteral("Short Band 2 Depth") },
    { 82, QStringLiteral("Short Band 2 Pan") },
    { 83, QStringLiteral("Short Band 2 Level") },
    { 84, QStringLiteral("Short Band 2 Sync") },

    { 85, QStringLiteral("Short Band 3 Low Cut Filter") },
    { 86, QStringLiteral("Short Band 3 High Cut Filter") },
    { 87, QStringLiteral("Short Band 3 Feedback") },
    { 88, QStringLiteral("Short Band 3 Wave") },
    { 89, QStringLiteral("Short Band 3 Phase") },
    { 90, QStringLiteral("Short Band 3 Tap") },
    { 91, QStringLiteral("Short Band 3 Speed") },
    { 92, QStringLiteral("Short Band 3 Depth") },
    { 93, QStringLiteral("Short Band 3 Pan") },
    { 94, QStringLiteral("Short Band 3 Level") },
    { 95, QStringLiteral("Short Band 3 Sync") },

    { 96, QStringLiteral("Short Band 4 Low Cut Filter") },
    { 97, QStringLiteral("Short Band 4 High Cut Filter") },
    { 98, QStringLiteral("Short Band 4 Feedback") },
    { 99, QStringLiteral("Short Band 4 Wave") },
    {100, QStringLiteral("Short Band 4 Phase") },
    {101, QStringLiteral("Short Band 4 Tap") },
    {102, QStringLiteral("Short Band 4 Speed") },
    {103, QStringLiteral("Short Band 4 Depth") },
    {104, QStringLiteral("Short Band 4 Pan") },
    {105, QStringLiteral("Short Band 4 Level") },
    {106, QStringLiteral("Short Band 4 Sync") }
};

const QMap<int, QString> ShortMediumLongModDlyKnobParameters =
{
    { 0, QStringLiteral("Short Band Delay Time") },
    { 1, QStringLiteral("Medium Band Delay Time") },
    { 4, QStringLiteral("Long Band Delay Time") },
    { 8, QStringLiteral("Effect Level") },
    { 9, QStringLiteral("Direct Level") },
    { 10, QStringLiteral("Direct Pan") },
    { 11, QStringLiteral("Wave Form") },

    { 19, QStringLiteral("Short Band Low Cut Filter") },
    { 20, QStringLiteral("Short Band High Cut Filter") },
    { 21, QStringLiteral("Short Band Feedback") },
    { 22, QStringLiteral("Short Band Wave") },
    { 23, QStringLiteral("Short Band Phase") },
    { 24, QStringLiteral("Short Band Tap") },
    { 25, QStringLiteral("Short Band Speed") },
    { 26, QStringLiteral("Short Band Depth") },
    { 27, QStringLiteral("Short Band Pan") },
    { 28, QStringLiteral("Short Band Level") },
    { 29, QStringLiteral("Short Band Sync") },

    { 30, QStringLiteral("Medium Band Low Cut Filter") },
    { 31, QStringLiteral("Medium Band High Cut Filter") },
    { 32, QStringLiteral("Medium Band Feedback") },
    { 33, QStringLiteral("Medium Band Tap 1 Wave") },
    { 34, QStringLiteral("Medium Band Tap 1 Phase") },
    { 35, QStringLiteral("Medium Band Tap 1 Tap") },
    { 36, QStringLiteral("Medium Band Tap 1 Speed") },
    { 37, QStringLiteral("Medium Band Tap 1 Depth") },
    { 38, QStringLiteral("Medium Band Tap 1 Pan") },
    { 39, QStringLiteral("Medium Band Tap 1 Level") },
    { 40, QStringLiteral("Medium Band Tap 1 Sync") },

    { 44, QStringLiteral("Medium Band Tap 2 Wave") },
    { 45, QStringLiteral("Medium Band Tap 2 Phase") },
    { 46, QStringLiteral("Medium Band Tap 2 Tap") },
    { 47, QStringLiteral("Medium Band Tap 2 Speed") },
    { 48, QStringLiteral("Medium Band Tap 2 Depth") },
    { 49, QStringLiteral("Medium Band Tap 2 Pan") },
    { 50, QStringLiteral("Medium Band Tap 2 Level") },
    { 51, QStringLiteral("Medium Band Tap 2 Sync") },

    { 55, QStringLiteral("Medium Band Tap 3 Wave") },
    { 56, QStringLiteral("Medium Band Tap 3 Phase") },
    { 57, QStringLiteral("Medium Band Tap 3 Tap") },
    { 58, QStringLiteral("Medium Band Tap 3 Speed") },
    { 59, QStringLiteral("Medium Band Tap 3 Depth") },
    { 60, QStringLiteral("Medium Band Tap 3 Pan") },
    { 61, QStringLiteral("Medium Band Tap 3 Level") },
    { 62, QStringLiteral("Medium Band Tap 3 Sync") },

    { 63, QStringLiteral("Long Band Low Cut Filter") },
    { 64, QStringLiteral("Long Band High Cut Filter") },
    { 65, QStringLiteral("Long Band Feedback") },
    { 66, QStringLiteral("Long Band Tap 1 Wave") },
    { 67, QStringLiteral("Long Band Tap 1 Phase") },
    { 68, QStringLiteral("Long Band Tap 1 Tap") },
    { 69, QStringLiteral("Long Band Tap 1 Speed") },
    { 70, QStringLiteral("Long Band Tap 1 Depth") },
    { 71, QStringLiteral("Long Band Tap 1 Pan") },
    { 72, QStringLiteral("Long Band Tap 1 Level") },
    { 73, QStringLiteral("Long Band Tap 1 Sync") },

    { 77, QStringLiteral("Long Band Tap 2 Wave") },
    { 78, QStringLiteral("Long Band Tap 2 Phase") },
    { 79, QStringLiteral("Long Band Tap 2 Tap") },
    { 80, QStringLiteral("Long Band Tap 2 Speed") },
    { 81, QStringLiteral("Long Band Tap 2 Depth") },
    { 82, QStringLiteral("Long Band Tap 2 Pan") },
    { 83, QStringLiteral("Long Band Tap 2 Level") },
    { 84, QStringLiteral("Long Band Tap 2 Sync") },

    { 88, QStringLiteral("Long Band Tap 3 Wave") },
    { 89, QStringLiteral("Long Band Tap 3 Phase") },
    { 90, QStringLiteral("Long Band Tap 3Tap") },
    { 91, QStringLiteral("Long Band Tap 3 Speed") },
    { 92, QStringLiteral("Long Band Tap 3 Depth") },
    { 93, QStringLiteral("Long Band Tap 3 Pan") },
    { 94, QStringLiteral("Long Band Tap 3 Level") },
    { 95, QStringLiteral("Long Band Tap 3 Sync") },

    { 99, QStringLiteral("Long Band Tap 4 Wave") },
    {100, QStringLiteral("Long Band Tap 4 Phase") },
    {101, QStringLiteral("Long Band Tap 4 Tap") },
    {102, QStringLiteral("Long Band Tap 4 Speed") },
    {103, QStringLiteral("Long Band Tap 4 Depth") },
    {104, QStringLiteral("Long Band Tap 4 Pan") },
    {105, QStringLiteral("Long Band Tap 4 Level") },
    {106, QStringLiteral("Long Band Tap 4 Sync") }
};

const QMap<int, QString> BassPreampKnobParameters =
{
    { 1, QStringLiteral("Parametric EQ Freq") },
    { 8, QStringLiteral("Gain") },
    { 9, QStringLiteral("Master") },
    { 11, QStringLiteral("Type") },
    { 19, QStringLiteral("Bass") },
    { 20, QStringLiteral("Low Middle") },
    { 21, QStringLiteral("Middle") },
    { 22, QStringLiteral("High Middle") },
    { 23, QStringLiteral("Treble") },
    { 25, QStringLiteral("Bass Freq") },
    { 26, QStringLiteral("Low Mid Freq") },
    { 27, QStringLiteral("Mid Freq") },
    { 28, QStringLiteral("High Mid Freq") },
    { 29, QStringLiteral("Treble Freq") },
    { 30, QStringLiteral("Parametric EQ Freq") },
    { 31, QStringLiteral("Parametric EQ Gain") },
    { 32, QStringLiteral("Gate") },
    { 33, QStringLiteral("Speaker Simulator") },
    { 34, QStringLiteral("Limiter") },
    { 35, QStringLiteral("Compressor Ratio") },
    { 36, QStringLiteral("Compressor Threshold") },
    { 37, QStringLiteral("Compressor Attack") },
    { 38, QStringLiteral("Compressor Release") },
    { 39, QStringLiteral("Compressor Gain") },
    { 40, QStringLiteral("Compressor Knee") }
};


#endif // KNOBPARAMETES_H
